create or alter procedure sp_oltp_produto(@data_carga datetime)
as
begin
	DECLARE @COD_PRODUTO INT, @NM_PRODUTO VARCHAR(100), @COD_CATEGORIA_PRODUTO INT, @COD_CATEGORIA INT, @CATEGORIA VARCHAR(100)

	DECLARE C_PRODUTO CURSOR FOR
	SELECT COD_PRODUTO,PRODUTO, COD_CATEGORIA FROM TB_PRODUTO
	OPEN C_PRODUTO
	FETCH C_PRODUTO INTO @COD_PRODUTO, @NM_PRODUTO, @COD_CATEGORIA_PRODUTO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		DECLARE C_CATEGORIA CURSOR FOR
		SELECT COD_CATEGORIA, CATEGORIA FROM TB_CATEGORIA
		OPEN C_CATEGORIA
		FETCH C_CATEGORIA INTO @COD_CATEGORIA, @CATEGORIA

		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			IF (@COD_CATEGORIA_PRODUTO = @COD_CATEGORIA)
			BEGIN
				INSERT INTO TB_AUX_PRODUTO VALUES (@data_carga, @COD_PRODUTO, @NM_PRODUTO, @COD_CATEGORIA, @CATEGORIA)
			END

			FETCH C_CATEGORIA INTO @COD_CATEGORIA, @CATEGORIA
		END

		CLOSE C_CATEGORIA
		DEALLOCATE C_CATEGORIA

		FETCH C_PRODUTO INTO @COD_PRODUTO, @NM_PRODUTO, @COD_CATEGORIA_PRODUTO
	END

	CLOSE C_PRODUTO
	DEALLOCATE C_PRODUTO
end


-- Teste

exec sp_oltp_produto '20230321'

select * from tb_aux_produto