create or alter procedure sp_oltp_tipo_pagamento(@data_carga datetime)
as
begin
	DECLARE @COD_PAGAMENTO INT, @TIPO_PAGAMENTO VARCHAR(100)

	DECLARE C_PAGAMENTO CURSOR FOR
	SELECT COD_TIPO_PAGAMENTO, TIPO_PAGAMENTO FROM TB_TIPO_PAGAMENTO
	OPEN C_PAGAMENTO
	FETCH C_PAGAMENTO INTO @COD_PAGAMENTO, @TIPO_PAGAMENTO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		INSERT INTO TB_AUX_TIPO_PAGAMENTO VALUES (@data_carga, @COD_PAGAMENTO, @TIPO_PAGAMENTO)

		FETCH C_PAGAMENTO INTO @COD_PAGAMENTO, @TIPO_PAGAMENTO
	END

	CLOSE C_PAGAMENTO
	DEALLOCATE C_PAGAMENTO
end



-- Teste

exec sp_oltp_tipo_pagamento '20230321'

select * from tb_aux_tipo_pagamento