CREATE DATABASE DIM_TEMPO

USE DIM_TEMPO

CREATE TABLE DIM_TEMPO (
	ID_TEMPO		BIGINT			NOT NULL	IDENTITY(1,1) PRIMARY KEY,
	NIVEL			VARCHAR(8)		NOT NULL	CHECK (NIVEL IN('DIA', 'MES', 'ANO')),
	DATA			DATETIME		NULL,
	DIA				INT				NULL,
	DIA_SEMANA		VARCHAR(50)		NULL,
	FIM_SEMANA		VARCHAR(5)		NULL		CHECK (FIM_SEMANA IN('SIM', 'NAO')),
	FERIADO			VARCHAR(100)	NULL,
	FL_FERIADO		VARCHAR(5)		NULL		CHECK (FL_FERIADO IN ('SIM', 'NAO')),
	MES				INT				NULL,
	NOME_MES		VARCHAR(100)	NULL,
	TRIMESTRE		INT				NULL,
	NOME_TRIMESTRE	VARCHAR(100)    NULL,
	SEMESTRE		INT				NULL,
	NOME_SEMESTRE	VARCHAR(100)	NULL,
	ANO				INT				NOT NULL
)

DROP TABLE DIM_TEMPO

CREATE TABLE DIM_FERIADO (
	ID_FERIADO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA DATE NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	TIPO VARCHAR(50) NOT NULL CHECK(TIPO IN('NACIONAL', 'ESTADUAL')),
	CONSTRAINT UK_FERIADO UNIQUE(DATA)
)

INSERT INTO DIM_FERIADO VALUES ('2023-09-07', 'DIA DA INDEPENDENCIA BRASILEIRA', 'NACIONAL')

CREATE OR ALTER PROCEDURE SP_DIM_TEMPO
@dt_inicial DATE,
@dt_final DATE
AS
BEGIN
	DECLARE @NIVEL VARCHAR(8), @DIA_SEMANA VARCHAR(50), @FIM_SEMANA VARCHAR(3), @NOME_MES VARCHAR(100), @TRIMESTRE DECIMAL(10,2), @NOME_TRIMESTRE VARCHAR(100), @SEMESTRE DECIMAL(10,2), @NOME_SEMESTRE VARCHAR(100)

	WHILE (@dt_inicial != @dt_final)
	BEGIN
		-- NOME DO DIA DA SEMANA
		SET @DIA_SEMANA = DATENAME(dw, @dt_inicial)

		-- SE É UM FIM DE SEMANA OU NÃO
		IF @DIA_SEMANA = 'Sexta-Feira' or @DIA_SEMANA = 'Sábado' or @DIA_SEMANA = 'Domingo'
		BEGIN
			SET @FIM_SEMANA = 'SIM'
		END
		ELSE
		BEGIN
			SET @FIM_SEMANA = 'NAO'
		END

		-- NOME DO MÊS
		SET @NOME_MES = DATENAME(MONTH, @dt_inicial)

		-- NÚMERO DO TRIMESTRE
		SET @TRIMESTRE = MONTH(@dt_inicial)
		SET @TRIMESTRE = CEILING(@TRIMESTRE / 3)

		-- NOME DO TRIMESTRE
		IF @TRIMESTRE = 1
		BEGIN
			SET @NOME_TRIMESTRE = 'Primeiro'
		END

		ELSE IF @TRIMESTRE = 2
		BEGIN
			SET @NOME_TRIMESTRE = 'Segundo'
		END

		ELSE IF @TRIMESTRE = 3
		BEGIN
			SET @NOME_TRIMESTRE = 'Terceiro'
		END

		ELSE IF @TRIMESTRE = 4
		BEGIN
			SET @NOME_TRIMESTRE = 'Quarto'
		END

		-- NÚMERO DO SEMESTRE
		SET @SEMESTRE = MONTH(@dt_inicial)
		SET @SEMESTRE = CEILING(@SEMESTRE / 6)

		-- NOME DO SEMESTRE
		IF @SEMESTRE = 1
		BEGIN
			SET @NOME_SEMESTRE = 'Primeiro'
		END

		ELSE IF @SEMESTRE = 2
		BEGIN
			SET @NOME_SEMESTRE = 'Segundo'
		END

		INSERT INTO DIM_TEMPO VALUES ('DIA', @dt_inicial, DAY(@dt_inicial), @DIA_SEMANA, NULL, NULL, 'NAO', MONTH(@dt_inicial), @NOME_MES, @TRIMESTRE, @NOME_TRIMESTRE, @SEMESTRE, @NOME_SEMESTRE, YEAR(@dt_inicial))

		SET @dt_inicial = DATEADD(DAY, 1, @dt_inicial)
	END
END

CREATE OR ALTER PROCEDURE SP_ATUALIZA_FERIADO_TEMPO
@ANO DATE
AS
BEGIN
	DECLARE @FERIADO VARCHAR(100), @DATA DATE
	DECLARE C_FERIADO CURSOR FOR
	SELECT DATA, DESCRICAO FROM DIM_FERIADO

	OPEN C_FERIADO

	FETCH C_FERIADO INTO @DATA, @FERIADO

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		UPDATE DIM_TEMPO
		SET FERIADO = @FERIADO, FL_FERIADO = 'SIM'
		WHERE DATA = @DATA

		FETCH C_FERIADO INTO @DATA, @FERIADO
	END

	CLOSE C_FERIADO
	DEALLOCATE C_FERIADO
END

CREATE OR ALTER PROCEDURE SP_ATUALIZA_FERIADO_TEMPO
@ANO DATE
AS
BEGIN
    BEGIN TRY
        DECLARE @FERIADO VARCHAR(100), @DATA DATE
        DECLARE @C_FERIADO CURSOR

        SET @C_FERIADO = CURSOR FOR
        SELECT DATA, DESCRICAO FROM DIM_FERIADO

        OPEN @C_FERIADO

        FETCH @C_FERIADO INTO @DATA, @FERIADO

        WHILE (@@FETCH_STATUS = 0)
        BEGIN
            UPDATE DIM_TEMPO
            SET FERIADO = @FERIADO, FL_FERIADO = 'SIM'
            WHERE DATA = @DATA

            FETCH @C_FERIADO INTO @DATA, @FERIADO
        END

        CLOSE @C_FERIADO
        DEALLOCATE @C_FERIADO
    END TRY
    BEGIN CATCH
        -- Adicione o tratamento de erro aqui (por exemplo, PRINT ERROR_MESSAGE())
    END CATCH
END


EXEC SP_DIM_TEMPO '2023-01-01', '2024-01-01';
EXEC SP_ATUALIZA_FERIADO_TEMPO '2023';

SELECT * FROM DIM_TEMPO
WHERE NOME_MES = 'Setembro'