CREATE DATABASE LAB_02

USE LAB_02

-- ESQUEMA OPERACIONAL

CREATE TABLE TB_FUNCIONARIO (
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	CARGO VARCHAR(50) NOT NULL,
	FUNCAO VARCHAR(50) NULL,
	SALARIO NUMERIC(10,2) NOT NULL,
	COD_SETOR INT NOT NULL REFERENCES TB_SETOR (COD_SETOR)
)

INSERT INTO TB_FUNCIONARIO VALUES (1, 'CAIO', '08810216520', 'ANALISTA DE DADOS', 'ANALISAR DADOS E GERAR RELATÓRIOS', 11519, 11)

CREATE TABLE TB_SETOR (
	COD_SETOR INT NOT NULL PRIMARY KEY,
	NM_SETOR VARCHAR(50) NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL REFERENCES TB_DEPARTAMENTO (COD_DEPARTAMENTO)
)

INSERT INTO TB_SETOR VALUES (11, 'ANÁLISE DE DADOS', 101)

CREATE TABLE TB_DEPARTAMENTO (
	COD_DEPARTAMENTO INT NOT NULL PRIMARY KEY,
	NM_DEPARTAMENTO VARCHAR(50) NOT NULL
)

INSERT INTO TB_DEPARTAMENTO VALUES (101, 'TI')

-- ESQUEMA DE ÁREA DE STAGING

CREATE TABLE TB_AUX_FUNCIONARIO (
	DATA_CARGA DATETIME NOT NULL,
	MATRICULA INT NOT NULL,
	NOME VARCHAR(60) NULL,
	CPF	VARCHAR(11) NULL,
	CARGO VARCHAR(50) NULL,
	FUNCAO VARCHAR(50) NULL,
	SALARIO NUMERIC(10,2) NULL,
	CODIGO_SETOR INT NULL,
	SETOR VARCHAR(50) NULL,
	CODIGO_DEPARTAMENTO INT NULL,
	DEPARTAMENTO VARCHAR(50) NULL,
)

-- ESQUEMA DIMENSIONAL

CREATE TABLE DIM_FUNCIONARIO (
	ID_FUNCIONARIO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MATRICULA INT NOT NULL,
	NOME VARCHAR(60) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	CARGO VARCHAR(50) NOT NULL,
	FUNCAO VARCHAR(50) NULL,
	SALARIO NUMERIC(10,2) NOT NULL,
	CODIGO_SETOR INT NULL,
	SETOR VARCHAR(50) NOT NULL,
	CODIGO_DEPARTAMENTO INT NULL,
	DEPARTAMENTO VARCHAR(50) NOT NULL,
	DT_INICIO DATETIME NOT NULL,
	DT_FIM DATETIME NULL,
	FL_CORRENTE VARCHAR(3) NOT NULL CHECK(FL_CORRENTE IN ('SIM', 'NAO'))
)

-- PROCEDIMENTO DA ÁREA OPERACIONAL PARA ÁREA STAGING

CREATE OR ALTER PROCEDURE SP_OLTP_FUNCIONARIO
@DATA_CARGA DATE
AS
BEGIN
	DECLARE @COD_DEPARTAMENTO INT, @NM_DEPARTAMENTO VARCHAR(50)

	DECLARE C_DEPARTAMENTO CURSOR FOR
	SELECT COD_DEPARTAMENTO, NM_DEPARTAMENTO FROM TB_DEPARTAMENTO

	OPEN C_DEPARTAMENTO
	FETCH C_DEPARTAMENTO INTO @COD_DEPARTAMENTO, @NM_DEPARTAMENTO
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		DECLARE @COD_SETOR INT, @NM_SETOR VARCHAR(50), @COD_DEPARTAMENTO_SETOR INT

		DECLARE C_SETOR CURSOR FOR
		SELECT COD_SETOR, NM_SETOR, COD_DEPARTAMENTO FROM TB_SETOR

		OPEN C_SETOR
		FETCH C_SETOR INTO @COD_SETOR, @NM_SETOR, @COD_DEPARTAMENTO_SETOR

		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			DECLARE @MATRICULA INT, @NOME VARCHAR(50), @CPF VARCHAR(11), @CARGO VARCHAR(50), @FUNCAO VARCHAR(50), @SALARIO NUMERIC(10,2), @COD_SETOR_FUNC INT

			DECLARE C_FUNC CURSOR FOR
			SELECT MATRICULA, NOME, CPF, CARGO, FUNCAO, SALARIO, COD_SETOR FROM TB_FUNCIONARIO

			OPEN C_FUNC
			FETCH C_FUNC INTO @MATRICULA, @NOME, @CPF, @CARGO, @FUNCAO, @SALARIO, @COD_SETOR_FUNC

			WHILE (@@FETCH_STATUS = 0)
			BEGIN
				IF (@COD_DEPARTAMENTO = @COD_DEPARTAMENTO_SETOR AND @COD_SETOR = @COD_SETOR_FUNC)
					INSERT INTO TB_AUX_FUNCIONARIO VALUES(@DATA_CARGA, @MATRICULA, @NOME, @CPF, @CARGO, @FUNCAO, @SALARIO, @COD_SETOR, @NM_SETOR, @COD_DEPARTAMENTO, @NM_DEPARTAMENTO)

				FETCH C_FUNC INTO @MATRICULA, @NOME, @CPF, @CARGO, @FUNCAO, @SALARIO, @COD_SETOR_FUNC
			END

			CLOSE C_FUNC
			DEALLOCATE C_FUNC

			FETCH C_SETOR INTO @COD_SETOR, @NM_SETOR, @COD_DEPARTAMENTO_SETOR
		END

		CLOSE C_SETOR
		DEALLOCATE C_SETOR

		FETCH C_DEPARTAMENTO INTO @COD_DEPARTAMENTO, @NM_DEPARTAMENTO
	END

	CLOSE C_DEPARTAMENTO
	DEALLOCATE C_DEPARTAMENTO
END

EXEC SP_OLTP_FUNCIONARIO '2024-02-18';

SELECT * FROM TB_AUX_FUNCIONARIO

CREATE OR ALTER PROCEDURE SP_DIM_FUNCIONARIO
AS
BEGIN
	DECLARE @DATA_CARGA DATE, @MATRICULA INT, @NOME VARCHAR(60), @CPF VARCHAR(11), @CARGO VARCHAR(50), @FUNCAO VARCHAR(50), @SALARIO NUMERIC(10,2), @CODIGO_SETOR INT, @SETOR VARCHAR(50), @CODIGO_DEPARTAMENTO INT, @DEPARTAMENTO VARCHAR(50)

	DECLARE C_STAGING CURSOR FOR
	SELECT * FROM TB_AUX_FUNCIONARIO
	OPEN C_STAGING
	FETCH C_STAGING INTO @DATA_CARGA, @MATRICULA, @NOME, @CPF, @CARGO, @FUNCAO, @SALARIO, @CODIGO_SETOR, @SETOR, @CODIGO_DEPARTAMENTO, @DEPARTAMENTO

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		INSERT INTO DIM_FUNCIONARIO VALUES (@MATRICULA, @NOME, @CPF, @CARGO, @FUNCAO, @SALARIO, @CODIGO_SETOR, @SETOR, @CODIGO_DEPARTAMENTO, @DEPARTAMENTO, @DATA_CARGA, NULL, 'SIM')

		FETCH C_STAGING INTO @DATA_CARGA, @MATRICULA, @NOME, @CPF, @CARGO, @FUNCAO, @SALARIO, @CODIGO_SETOR, @SETOR, @CODIGO_DEPARTAMENTO, @DEPARTAMENTO
	END


END